### ISSUE TITLE
https only?

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/specs#18]
Looking at https://github.com/libscie/https-checker, I thought about whether the p2pcommons spec is strictly `https` only. The only part where currently an `http` url can be inserted is in the `links` property. Should we say that all of these need to be `https`?

This upside in security comes at the cost of resources being harder to link to when only available in `http` and having to be rehosted or proxied to (if possible).

**Comment by chartgerink** [comment]
That is a good point! We could add a SHOULD clause that warns for any non-https? That way, writing a linter that tries for `https` is in line and we can still accept `http` if really necessary?

https://github.com/p2pcommons/specs/pull/17

**Comment by juliangruber** [comment]
Oh great idea for the linter to check if an https version is available!
