### ISSUE TITLE
Whitespace in title

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/specs#28]
Currently a title of `" "` is valid, as it's not empty. I propose we specify that after trimming whitespace at beginning and end the character count needs to be >0. The upper limit of 300 can be applied without the trimming still.

EDIT @jameslibscie: We are going to allow leading and trailing whitespace in titles, but a title must not consist only of whitespace.

**Comment by juliangruber** [comment]
```js
/^\s*\S.{1,299}\s*/$/
```

I think does it

**Comment by jameslibscie** [comment]
Is it maybe easier to specify that the title (perhaps all fields?) should always be trimmed?

**Comment by juliangruber** [comment]
You mean that the title musn't contain leading or trailing whitespace?

**Comment by jameslibscie** [comment]
Indeed

**Comment by juliangruber** [comment]
That could be the simplest solution! Mustn't start or end with whitespace and be 1-300 characters long

**Comment by juliangruber** [comment]
```js
/^\S(.{0,298}\S)?$/
```

I think! It starts with a non-space character. It ends with a non-space character. In between can come any 0-298 characters

**Comment by jameslibscie** [comment]
As per yesterday's meeting, we decided on banning whitespace-only titles, rather than enforcing that the title be trimmed.
