### ISSUE TITLE
Update module spec to daemon integration

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/specs#31]
The [`@p2pcommons/sdk-js`](https://github.com/p2pcommons/sdk-js) is shifting towards using the `hyperdrive-daemon` implementation, which provides a generic environment for storing Hyperdrives. 

This means that module storage is now compartmentalised from the local databases.

- [ ] Update the storage of Hyperdrives
- [ ] Retain the use of `~/.p2pcommons` for local databases

**Comment by chartgerink** [comment]
@dpaez any additional changes that we'd need to take into account based on the integration with `hyperdrive-daemon`?

**Comment by dpaez** [comment]
From what I have tried with this open [PR](https://github.com/p2pcommons/sdk-js/pull/153) and what is coming on a new PR with fuse support I can add the following:
- we still make use of the `~/.p2pcommons/` dir where our internal db lives.
- about the hyperdrive storage, we now consider fuse and non-fuse users:
  - **fuse users**, we will mount modules directories inside of the default storage for fuse, ie: `~/Hyperdrive/`. Here we can mount everything inside a particular mount, like `~/Hyperdrive/p2pcommons`. And inside there we can put the modules, or we can just drop them, ie mount the, inside the root, ie: `~/Hyperdrive/myModuleDir`. **Caveat:** With fuse we don't have a way to know the drive key before mounting it. So, here the change will imply to drop the `<hash>+<version>` convention that we were using for modules directory names.
  - **non-fuse users**, we can choose any directory as the working directory and from there we can use the import and export methods (there is an [open PR](https://github.com/hypercore-protocol/hyperdrive-daemon-client/pull/13) for adding these methods to the `hyperdrive-daemon-client` interface). **Caveat**: when doing the import and export the return is mirror-folder-like-watcher, an event emitter that the consumer should handle.

**Comment by dpaez** [comment]
In short, the caveats indicates that there is a conflict with the interoperability spec, the caching section (https://github.com/p2pcommons/specs/blob/master/interoperability.md#caching-modules)
