### ISSUE TITLE
registration to one or multiple authors?

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/specs#43]
A module is registered when one _or more_ of its authors have added it to their profile, right? The specs aren't mentioning multiple authors here.

> Registration
> Registered modules must be of p2pcommons.type: content (i.e., origin module) and MUST be registered to modules of p2pcommons.type: profile (i.e., destination module).
>
> Registration MUST NOT occur if the origin or destination modules are invalid. Registration SHOULD NOT occur if p2pcommons.authors is empty. The destination module MUST be writable.
>
> Registration MUST result in the addition of a valid Hyperdrive key to the p2pcommons.contents property of the destination module. The registered Hyperdrive key MUST be that of the specified origin module.
>
> It is RECOMMENDED to verify whether the origin module contains the destination module's Hyperdrive key in the authors property (see also Verification).

**Comment by chartgerink** [comment]
Yup :) 

Registration is the action taken by any author. Where it says "Registered modules" right now, it should technically be "To be registered modules". 

In that sense, a module can be registered by all or part of the authors. "Registered" is very different from "Verified", which is when all the authors that are assigned by the content module also have it listed in their profile as authored content.

I am not sure whether we really use the nomenclature of registered anywhere as a state?

**Comment by juliangruber** [comment]
Ah you're right, this is a remnant of an old state of Hypergraph where there could only be one author in the app. Thanks for the quick answer :)
