### ISSUE TITLE
module.license

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/specs#7]
From https://github.com/hypergraph-xyz/cli/issues/16:

> The license is also included in the profile. That is not necessary in the spec, but we could add it? What are your thoughts?

> Better to be more explicit imo, otherwise if some person finds the folder how are they going to know what the license is? Alternatively, we could also link to the spec instead, which would be even more self descriptive.

I'm not sure now I understand the original question. Is it about whether we should include the .license in modules at all, or whether we need a license for a profile module?

**Comment by chartgerink** [comment]
Currently, the specification mandates a license for modules of `type: content`. I think it's a good choice to extend the spec for modules of `type: profile` to do the same. 😊

Will fix and reference.

**Comment by chartgerink** [comment]
Double checked and confirmed in 6253ed3d61198780e25802ae4b2a69e31936958e
